FROM node:13.8.0-stretch-slim

RUN mkdir /app
WORKDIR /app

ADD config/ ./config
ADD controllers/ ./controllers
ADD models/ ./models
ADD routes/ ./routes
ADD [".env", "package.json", "package-lock.json", "server.js", "."]

RUN npm install

CMD npm start